name: Build Docker image

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out
      uses: actions/checkout@v2

    - name: Login to GitHub
      uses: docker/login-action@v1.6.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build the Docker image
      run: docker build . --file Dockerfile
    
    - name: Push package
      uses: docker/build-push-action@v1
      with:
        repository: marvinisaac/docker-php-image/docker-php-image
        tags: latest
        tag_with_ref: true
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
